# Generated by Django 4.2.6 on 2026-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IQACMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('joint_coordinator', 'Joint Coordinator'), ('member', 'Member')], default='member', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'name', 'id'],
            },
        ),
    ]
