# Generated by Django 4.2.6 on 2026-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_iqacmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqacmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='iqac/'),
        ),
    ]
