# Generated by Django 4.2.6 on 2026-02-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.galleryitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
