# Generated by Django 4.2.6 on 2026-02-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_addoncourse'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE myapp_addoncourse CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
