# Generated by Django 4.2.6 on 2026-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_addoncourse_utf8mb4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeSyllabusCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('fyugp', 'UG - FYUGP'), ('ug', 'UG'), ('pg', 'PG')], db_index=True, default='ug', max_length=16)),
                ('syllabus_pdf', models.FileField(upload_to='syllabus/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course_type', 'title', 'id'],
            },
        ),
    ]
